language: go

go:
- "1.11.x"

env:
- GO111MODULE=on 

before_install:
- export PATH=$PATH:$GOPATH/bin
- pushd $GOPATH
- mkdir go-tools
- cd go-tools
- go mod init go-tools
- go get -u github.com/mattn/goveralls
- cd ..
- curl -L https://git.io/vp6lP | sh
- popd
- env GO111MODULE=off go generate ./...

script:
  - go build 
  
after_script:
- go mod vendor
- env GO111MODULE=off gometalinter -e vendor --deadline=1000s ./...

