language: go

go:
- "1.10.x"

before_install:
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update
- go generate -x ./...

script:

after_script:
- gometalinter -e bindata --deadline=1000s ./...

